# Generated by Django 3.0 on 2020-01-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264, unique=True)),
                ('songs', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('duration', models.CharField(max_length=264)),
                ('url', models.URLField(unique=True)),
                ('img_url', models.URLField(unique=True)),
                ('channel_name', models.CharField(max_length=264)),
                ('channel_url', models.URLField()),
                ('path', models.FilePathField(blank=True, unique=True)),
                ('uploaded', models.CharField(max_length=264)),
                ('views', models.CharField(max_length=264)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
