# Generated by Django 3.0 on 2020-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='path',
            field=models.FilePathField(path='D:\\Workspace\\Python\\yt_music\\media', unique=True),
        ),
    ]
