# Generated by Django 3.0 on 2019-12-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_path',
            field=models.FilePathField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
