# Generated by Django 3.0 on 2020-01-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200102_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='path',
            field=models.FilePathField(path='D:\\Workspace\\Python\\yt_music\\media'),
        ),
    ]
